In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn 

In [17]:
pip install statsmodels

Note: you may need to restart the kernel to use updated packages.


In [18]:
import statsmodels.formula.api as sm

In [19]:
#importing the dataset
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:,:-1].values 
y = dataset.iloc[:,4].values

In [20]:
# encoding categorical data
# encoding the independent varaible ie the label

from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_X = LabelEncoder()
(X[:,3])=labelencoder_X.fit_transform(X[:,3])

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [3])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

X = ct.fit_transform(X)

In [24]:
X

array([[1, 0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1.0, 0.0, 0.0, 78013.11, 121597.55, 264

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state = 0)

In [27]:
X_train

array([[1, 0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [1, 0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1, 0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [1, 1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [1, 0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [1, 0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [1, 0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [1, 0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [1, 0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [1, 1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1, 1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [1, 1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [1, 0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1, 0.

In [29]:
X_test

array([[1, 0.0, 1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [1, 1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1, 0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1, 0.0, 0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [1, 0.0, 0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1, 0.0, 1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1, 0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42]], dtype=object)

In [30]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [31]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [65]:
from sklearn.linear_model import LinearRegression
import statsmodels.regression.linear_model as lm
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [53]:

# predicting the tests set results
y_pred = regressor.predict(X_test)

In [54]:
y_pred

array([103015.20159794, 132582.27760816, 132447.73845175,  71976.09851259,
       178537.48221058, 116161.24230167,  67851.69209677,  98791.73374686,
       113969.43533014, 167921.06569553])

In [55]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [56]:
# compare real and predicted profit

In [68]:
X = np.append(np.ones((50,1)).astype(int) ,values=X , axis=1)

In [69]:
# below we create a matrix containing only high impact independent varaibles so remove one by one

In [76]:
X_opt = X[:,[0,1,2,3,4,5]]

In [77]:
X_opt

array([[1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 1.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [1, 1, 1, 1, 0.0, 1.0],
       [1, 1, 1, 1, 0.0, 0.0],
       [

In [78]:
X_opt = np.array(X_opt, dtype=float)

In [79]:
X_opt

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0., 0.],
       [1.

In [74]:

regressor_ols = lm.OLS(endog = y,exog = X_opt).fit()

In [80]:
import statsmodels.api as sm

In [81]:
# above we have fit the model with all possile predictors

In [82]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5748
Date:                Mon, 17 Aug 2020   Prob (F-statistic):              0.567
Time:                        04:24:47   Log-Likelihood:                -600.05
No. Observations:                  50   AIC:                             1206.
Df Residuals:                      47   BIC:                             1212.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x1          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x2          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x3          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x4         -9851.2712   1.39e+04     -0.706      0.483   -3.79e+04    1.82e+04
x5          5017.5779   1.42e+04      0.354      0.725   -2.35e+04    3.35e+04
==============================================================================
Omnibus:                        0.111   Durbin-Watson:                   0.081
Prob(Omnibus):                  0.946   Jarque-Bera (JB):                0.207
Skew:                           0.104   Prob(JB):                        0.902
Kurtosis:                       2.762   Cond. No.                     6.54e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.93e-36. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [84]:
# above see p values the lower the p valuse the more significance it will be select highest and remove it varaibles

In [86]:
X_opt = X[:,[0,1,2,3,4,5]]
X_opt = np.array(X_opt, dtype=float)
regressor_ols = lm.OLS(endog = y,exog = X_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5748
Date:                Mon, 17 Aug 2020   Prob (F-statistic):              0.567
Time:                        04:31:03   Log-Likelihood:                -600.05
No. Observations:                  50   AIC:                             1206.
Df Residuals:                      47   BIC:                             1212.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x1          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x2          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x3          2.844e+04   2465.409     11.535      0.000    2.35e+04    3.34e+04
x4         -9851.2712   1.39e+04     -0.706      0.483   -3.79e+04    1.82e+04
x5          5017.5779   1.42e+04      0.354      0.725   -2.35e+04    3.35e+04
==============================================================================
Omnibus:                        0.111   Durbin-Watson:                   0.081
Prob(Omnibus):                  0.946   Jarque-Bera (JB):                0.207
Skew:                           0.104   Prob(JB):                        0.902
Kurtosis:                       2.762   Cond. No.                     6.54e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.93e-36. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""